language: android
dist: trusty

# This is needed since running robolectric on api 29 requires java 9
jdk: openjdk9

android:
  components:
    - build-tools-28.0.3
    - android-29
    - extra

script:
  - ./gradlew clean testDebug ktlintCheck
